version: "2.3"
services:
  detectron2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_USER: ${USER}
    image: detectron2
    container_name: detectron2
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    shm_size: "10gb"
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      # - $HOME/.Xauthority:/root/.Xauthority
      # - XAUTHORITY=/root/.Xauthority
      - ./src:/home/${USER}/workspace/src
      - ./catkin_src:/home/${USER}/workspace/catkin_ws/src
      - ./datasets:/home/${USER}/workspace/datasets
      - ./configs:/home/${USER}/workspace/configs
      - ./output:/home/${USER}/workspace/output
    environment:
      - DISPLAY=host.docker.internal${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - ROS_IP=detectron2
      - ROS_MASTER_URI=http://${ROS_MASTER_IP:-127.0.0.1}:11311
    networks:
      - ros_dev_external
    privileged: true
    tty: true
    # Uncomment with proper source to access webcam from docker
    # devices:
    #   - /dev/video0:/dev/video0
    working_dir: /home/${USER}/workspace
    command: bash -c "cd catkin_ws && catkin clean -b && catkin build && /bin/bash"

networks:
  ros_dev_external:
    external: true
